name: Isometric Contribution Calendar

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-calendar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate isometric contributions calendar
        uses: lowlighter/isometric-contributions@latest
        with:
          user: t0ll1v3r
          output: isometric-contributions.svg

      - name: Commit and push generated calendar
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add isometric-contributions.svg
          git commit -m "chore: update isometric contributions calendar" || echo "No changes to commit"
          git push
