name: Metrics

on:
  schedule: [{cron: "0 0 * * *"}] # Runs every day at midnight
  push: {branches: ["main"]}
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          config_timezone: America/New_York
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_followup: yes
          plugin_lines: yes
