name: Metrics

on:
  schedule:
    - cron: '0 0 * * *'         # every night at 00:00 UTC
  workflow_dispatch:            # manual trigger in Actions tab

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: header

          #–– core settings
          user: t0ll1v3r
          # template: classic

          plugin_isocalendar: yes
          plugin_overview: yes
          plugin_repositories: yes
          plugin_repositories_featured: t0ll1v3r/USB_HID_CompositeImplementation, t0ll1v3r/ActuatedFoodCutter, t0ll1v3r/EC413, t0ll1v3r/EC330
          
          plugin_stars: no
          plugin_issues: no
          plugin_pull_requests: no
          plugin_commit_activity: no
